import type { IncomingApplication } from '@/types/domain';

/**
 * Mock data for the institution admin portal.
 *
 * In Phase 4, this becomes API calls scoped to the logged-in admin's institution.
 * For now we hard-code "logged in as CBU admin" and only show CBU applications.
 */

/** The institution this admin user manages */
export const ADMIN_INSTITUTION_ID = 'cbu';

export const incomingApplications: IncomingApplication[] = [
  {
    id: 'in-1',
    programmeId: 'cbu-cs',
    programmeName: 'BSc Computer Science',
    status: 'submitted',
    submittedAt: '2025-04-22T09:14:00Z',
    lastUpdated: '2025-04-22T09:14:00Z',
    applicant: {
      fullName: 'Emmanuel Siamoonga',
      email: 'emmanuel@cbu.ac.zm',
      phone: '+260 977 123 456',
      province: 'Copperbelt',
      nrc: '231456/78/1',
      dateOfBirth: '2002-04-15',
      grades: [
        { subject: 'Mathematics',          minGrade: 2 },
        { subject: 'English Language',      minGrade: 3 },
        { subject: 'Physics',               minGrade: 2 },
        { subject: 'Additional Mathematics', minGrade: 3 },
      ],
      statement: 'I have always been fascinated by how software shapes everyday life in Zambia, from mobile money to school attendance systems. After completing my secondary education at Mukuba High School, I taught myself the basics of HTML and Python through community internet hours, and built a small attendance app for my church youth group. I want to study Computer Science at CBU because of its strong engineering tradition and the chance to learn from staff who have published in the field. After graduating I hope to build software that solves problems specific to the Zambian context.',
      documentNames: ['NRC.pdf', 'Grade12_Certificate.pdf', 'Transcript.pdf', 'Passport_Photo.jpg'],
    },
  },
  {
    id: 'in-2',
    programmeId: 'cbu-cs',
    programmeName: 'BSc Computer Science',
    status: 'under_review',
    submittedAt: '2025-04-20T14:02:00Z',
    lastUpdated: '2025-04-23T10:00:00Z',
    applicant: {
      fullName: 'Chanda Mwape',
      email: 'chanda.mwape@example.com',
      phone: '+260 966 234 567',
      province: 'Copperbelt',
      nrc: '198452/77/2',
      dateOfBirth: '2003-07-22',
      grades: [
        { subject: 'Mathematics',     minGrade: 3 },
        { subject: 'English Language', minGrade: 4 },
        { subject: 'Physics',          minGrade: 3 },
      ],
      statement: 'My passion for computing began when I built a small inventory tracker for my family business in Kitwe. Studying Computer Science at CBU would give me the rigorous foundation I need to scale that early curiosity into a career.',
      documentNames: ['NRC.pdf', 'Grade12_Certificate.pdf', 'Photo.jpg'],
    },
    internalNote: 'Strong personal statement. Verify Maths grade — possible typo on transcript.',
  },
  {
    id: 'in-3',
    programmeId: 'cbu-cs',
    programmeName: 'BSc Computer Science',
    status: 'accepted',
    submittedAt: '2025-04-15T11:30:00Z',
    decisionAt: '2025-04-21T16:00:00Z',
    lastUpdated: '2025-04-21T16:00:00Z',
    applicant: {
      fullName: 'Mutale Bwalya',
      email: 'mutale.b@example.com',
      phone: '+260 977 345 678',
      province: 'Lusaka',
      nrc: '276843/22/9',
      dateOfBirth: '2002-11-03',
      grades: [
        { subject: 'Mathematics',     minGrade: 1 },
        { subject: 'Physics',          minGrade: 2 },
        { subject: 'English Language', minGrade: 4 },
      ],
      statement: 'Top of my class at Roma Girls Secondary, I am confident I have what it takes to excel in BSc Computer Science.',
      documentNames: ['NRC.pdf', 'Grade12_Certificate.pdf', 'Transcript.pdf', 'Photo.jpg', 'Birth_Cert.pdf'],
    },
  },
  {
    id: 'in-4',
    programmeId: 'cbu-se',
    programmeName: 'BEng Software Engineering',
    status: 'submitted',
    submittedAt: '2025-04-23T08:00:00Z',
    lastUpdated: '2025-04-23T08:00:00Z',
    applicant: {
      fullName: 'Namwinga Tembo',
      email: 'namwinga.t@example.com',
      phone: '+260 955 456 789',
      province: 'Eastern',
      nrc: '345672/91/4',
      dateOfBirth: '2003-02-18',
      grades: [
        { subject: 'Mathematics',     minGrade: 2 },
        { subject: 'Physics',          minGrade: 3 },
        { subject: 'English Language', minGrade: 4 },
      ],
      statement: 'I want to be a software engineer who designs systems that work reliably even on slow connections — something I struggled with growing up in Chipata.',
      documentNames: ['NRC.pdf', 'Grade12_Certificate.pdf', 'Photo.jpg'],
    },
  },
  {
    id: 'in-5',
    programmeId: 'cbu-se',
    programmeName: 'BEng Software Engineering',
    status: 'under_review',
    submittedAt: '2025-04-19T15:40:00Z',
    lastUpdated: '2025-04-22T11:15:00Z',
    applicant: {
      fullName: 'Tafadzwa Banda',
      email: 'tafadzwa.b@example.com',
      phone: '+260 966 567 890',
      province: 'Lusaka',
      nrc: '412938/87/3',
      dateOfBirth: '2002-09-14',
      grades: [
        { subject: 'Mathematics',     minGrade: 3 },
        { subject: 'Physics',          minGrade: 4 },
        { subject: 'English Language', minGrade: 5 },
      ],
      statement: 'Software is the future of African industry. I want to be part of building it from Zambia.',
      documentNames: ['NRC.pdf', 'Grade12_Certificate.pdf'],
    },
    internalNote: 'Documents incomplete — request transcript before deciding.',
  },
  {
    id: 'in-6',
    programmeId: 'cbu-mining',
    programmeName: 'BEng Mining Engineering',
    status: 'submitted',
    submittedAt: '2025-04-21T10:10:00Z',
    lastUpdated: '2025-04-21T10:10:00Z',
    applicant: {
      fullName: 'Joshua Phiri',
      email: 'joshua.phiri@example.com',
      phone: '+260 977 678 901',
      province: 'Copperbelt',
      nrc: '503827/19/8',
      dateOfBirth: '2003-05-30',
      grades: [
        { subject: 'Mathematics',     minGrade: 3 },
        { subject: 'Physics',          minGrade: 3 },
        { subject: 'Chemistry',        minGrade: 4 },
      ],
      statement: 'My father was a miner in Mufulira for 25 years. I want to pursue Mining Engineering not only to follow his path, but to bring modern safety practices to Zambian mines.',
      documentNames: ['NRC.pdf', 'Grade12_Certificate.pdf', 'Transcript.pdf', 'Photo.jpg'],
    },
  },
  {
    id: 'in-7',
    programmeId: 'cbu-mining',
    programmeName: 'BEng Mining Engineering',
    status: 'rejected',
    submittedAt: '2025-04-12T13:20:00Z',
    decisionAt: '2025-04-18T09:30:00Z',
    lastUpdated: '2025-04-18T09:30:00Z',
    applicant: {
      fullName: 'Boyd Sakala',
      email: 'boyd.s@example.com',
      phone: '+260 966 789 012',
      province: 'Northern',
      nrc: '614720/55/7',
      dateOfBirth: '2002-12-08',
      grades: [
        { subject: 'Mathematics',     minGrade: 6 },
        { subject: 'Physics',          minGrade: 7 },
        { subject: 'Chemistry',        minGrade: 5 },
      ],
      statement: 'I am eager to study Mining Engineering at CBU.',
      documentNames: ['NRC.pdf', 'Grade12_Certificate.pdf'],
    },
    internalNote: 'Did not meet minimum grade thresholds. Encourage to apply again next cycle.',
  },
  {
    id: 'in-8',
    programmeId: 'cbu-cs',
    programmeName: 'BSc Computer Science',
    status: 'waitlisted',
    submittedAt: '2025-04-17T17:45:00Z',
    decisionAt: '2025-04-22T14:00:00Z',
    lastUpdated: '2025-04-22T14:00:00Z',
    applicant: {
      fullName: 'Lubinda Imenda',
      email: 'lubinda.i@example.com',
      phone: '+260 955 890 123',
      province: 'Western',
      nrc: '728193/02/6',
      dateOfBirth: '2003-08-19',
      grades: [
        { subject: 'Mathematics',     minGrade: 4 },
        { subject: 'English Language', minGrade: 5 },
        { subject: 'Physics',          minGrade: 5 },
      ],
      statement: 'My grades are at the threshold but I have strong project work in Python from a community coding club in Mongu, which I hope demonstrates capability beyond the test scores.',
      documentNames: ['NRC.pdf', 'Grade12_Certificate.pdf', 'Transcript.pdf', 'Photo.jpg'],
    },
    internalNote: 'On the waitlist. Reconsider if first-round offers decline.',
  },
];
